name: Makefile CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Generate developer key
      run: |
        openssl genrsa -out developer_key.pem 4096
        openssl pkcs8 -topk8 -inform PEM -outform DER -in developer_key.pem -out developer_key.der -nocrypt

    - name: Build with Monkey C
      run: |
        wget https://developer.garmin.com/downloads/connect-iq/sdks/connectiq-sdk-lin-6.2.1-2023-06-26-124cb49c5.zip
        unzip connectiq-sdk-lin-6.2.1-2023-06-26-124cb49c5.zip
        echo "sdk.location=$(pwd)" > local.properties
        export PATH=$PATH:$(pwd)/bin
        cd widget
        monkeyc -y ../developer_key.der -f monkey.jungle -o output.prg

