name: Makefile CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup connect-iq-sdk-manager-cli
      env:
        GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      run: |
        curl -s https://raw.githubusercontent.com/lindell/connect-iq-sdk-manager-cli/master/install.sh | sh
        connect-iq-sdk-manager login

    - name: Download devices
      run:  connect-iq-sdk-manager download --manifest=widget/manifest.xml

    - name: Get SDK
      run: |
        mkdir ~/sdk
        cd ~/sdk
        wget https://developer.garmin.com/downloads/connect-iq/sdks/connectiq-sdk-lin-4.1.4-2022-06-07-f86da2dee.zip
        unzip -qq connectiq-sdk-lin-4.1.4-2022-06-07-f86da2dee.zip
        echo ~/sdk/bin >> $GITHUB_PATH

    - name: Set SDK location
      run: |
        cd widget
        echo "sdk.location=~/sdk" > local.properties  

    - name: Generate developer key
      run: |
        openssl genrsa -out ~/developer_key.pem 4096
        openssl pkcs8 -topk8 -inform PEM -outform DER -in ~/developer_key.pem -out ~/developer_key.der -nocrypt

    - name: Build prg file
      run: |
        cd widget
        monkeyc -y ~/developer_key.der -f monkey.jungle -w -o /tmp/output.prg

    - name: Build iq file
      run: |
        cd widget
        monkeyc -y ~/developer_key.der -f monkey.jungle -w -e -o /tmp/output.iq
